/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import Controllers.MachineController;
import app.App;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    MachineController machineController;

    @Before
    public void init() {
        machineController = MachineController.getInstance();
        machineController.createMachine("machine", "abc");
    }

    @Test public void testSomeLibraryMethod() {
        App classUnderTest = new App();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testStateIint() {
        assertEquals(machineController.insertMoney(0.50), "null");
        assertEquals(machineController.selectProduct("Coke"), "null");
        assertEquals(machineController.initialize(), "Machine Initialized");
        assertEquals(machineController.insertMoney(0.50), "0.5");
        assertEquals(machineController.insertMoney(0.90), "Accepted coins:[0.05,0.1,0.2,0.5,1.0,2.0]");
    }

    @Test public void testProductServe() {
        assertEquals(machineController.initialize(), "Machine Initialized");
        assertEquals(machineController.insertMoney(0.50), "0.5");
        assertEquals(machineController.insertMoney(1.0), "1.5");
        assertEquals(machineController.selectProduct("Coke"), "{\"Served\":{\"Change\":0.0,\"Product\":\"Coke\"}}");
        assertEquals(machineController.insertMoney(2.0), "2.0");
        assertEquals(machineController.selectProduct("Coke"), "{\"Served\":{\"Change\":0.5,\"Product\":\"Coke\"}}");

        System.out.println(machineController.selectProduct("Coke"));

    }

}
